name: InventoryGUI
version: $apiVersion
api-version: 1.16
main: org.projecttl.api.inventorygui.InventoryGUI

commands:
  gui:
    description: You can see api description or open test gui.
    usage: /gui test